routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['prefix' => '/', 'as' => 'shop.'], function () {
  Route::match( array( 'GET' ), '/', array('as' => 'welcome', 'uses' => 'ShopController@welcome'));
  Route::match( array( 'GET' ), '/buscar-produtos', array('as' => 'search', 'uses' => 'ShopController@search'));
  Route::match( array( 'GET' ), '/{ID}/produto', array('as' => 'show', 'uses' => 'ShopController@show'));
  Route::match( array( 'POST' ), '/adicionar', array('as' => 'add', 'uses' => 'ShopController@add'));
  Route::match( array( 'PUT' ), '/alterar', array('as' => 'update', 'uses' => 'ShopController@update'));
  Route::match( array( 'DELETE' ), '/excluir', array('as' => 'destroy', 'uses' => 'ShopController@destroy'));
  Route::match( array( 'GET', 'POST' ), '/finalizar', array('as' => 'finish', 'uses' => 'ShopController@finish'))->middleware('auth');
});

Auth::routes();

Route::group(['prefix' => 'painel'/*, 'middleware' => 'dash'*/, 'as' => 'dash.'], function () {
  Route::match( array( 'GET' ), '/', array('as' => 'index', 'uses' => 'Dash\DashController@index'));
  Route::match( array( 'GET' ), '/sair', array('as' => 'logout', 'uses' => 'Dash\DashController@logout'));
  Route::match( array( 'GET' ), '/minha-conta', array('as' => 'myaccount', 'uses' => 'Dash\UserController@myaccount'));
  Route::match( array( 'GET', 'PATCH' ), '/configuracoes', array('as' => 'configs', 'uses' => 'Dash\ConfigController@index'));
  Route::group(['prefix' => '/usuarios', 'as' => 'users.'], function () {
    Route::match( array( 'GET', ), '/', array('as' => 'list', 'uses' => 'Dash\UserController@all'));
    Route::match( array( 'GET', 'POST' ), '/novo', array('as' => 'create', 'uses' => 'Dash\UserController@create'));
    Route::match( array( 'GET', 'PATCH' ), '/{ID}', array('as' => 'edit', 'uses' => 'Dash\UserController@edit'));
    Route::match( array( 'DELETE' ), '/{ID}', array('as' => 'destroy', 'uses' => 'Dash\UserController@destroy'));
  });
  Route::group(['prefix' => '/produtos', 'as' => 'products.'], function () {
    Route::match( array( 'GET', ), '/todos', array('as' => 'list', 'uses' => 'Dash\ProductController@all'));
    Route::match( array( 'GET', 'POST' ), '/novo', array('as' => 'create', 'uses' => 'Dash\ProductController@create'));
    Route::match( array( 'GET', 'PATCH' ), '/{ID}', array('as' => 'edit', 'uses' => 'Dash\ProductController@edit'));
    Route::match( array( 'DELETE' ), '/{ID}', array('as' => 'destroy', 'uses' => 'Dash\ProductController@destroy'));
  });
  Route::group(['prefix' => '/estoque', 'as' => 'stock.'], function () {
    Route::match( array( 'GET' ), '/', array('as' => 'list', 'uses' => 'Dash\StockController@all'));
  });
  Route::group(['prefix' => '/pedidos', 'as' => 'orders.'], function () {
    Route::match( array( 'GET', ), '/', array('as' => 'list', 'uses' => 'Dash\OrderController@all'));
    Route::match( array( 'GET', 'PATCH' ), '/{ID}', array('as' => 'edit', 'uses' => 'Dash\OrderController@show'));
    Route::match( array( 'GET', 'PATCH' ), '/{ID}/editar', array('as' => 'edit', 'uses' => 'Dash\OrderController@edit'));
  });
  Route::group(['prefix' => '/mala-direta', 'as' => 'directmail.'], function () {
    Route::match( array( 'GET', 'POST' ), '/', array('as' => 'list', 'uses' => 'Dash\DirectEmailController@all'));
    Route::match( array( 'GET', 'PATCH' ), '/{ID}', array('as' => 'edit', 'uses' => 'Dash\DirectEmailController@edit'));
    Route::match( array( 'GET', '' ), '/{ID}/enviar', array('as' => 'send', 'uses' => 'Dash\DirectEmailController@send'));
    Route::match( array( 'DELETE' ), '/{ID}', array('as' => 'destroy', 'uses' => 'Dash\DirectEmailController@destroy'));
  });
});

app/Http/Controllers/ShopController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

use Gloudemans\Shoppingcart\Facades\Cart;

use App\Models\Products;

class ShopController extends Controller
{
    public function welcome(Request $request)
    {
      return view('shop.welcome');
    }

    public function search(Request $request)
    {
      $products = Products::where('name', 'LIKE', '%'.$request->name.'%')
                        ->orwhere('sku', 'LIKE', '%'.$request->name.'%')
                        ->get();
      return view('shop.list', compact('products'));
    }

    public function show($id)
    {
      $product = Products::find($id);
      return view('shop.show', compact('product'));
    }

    public function add(Request $request)
    {
      $product = Products::find($request->id);
      $attributes['photo'] = $product->photo;      
      Cart::add($request->id, $product->name, 1, $product->price, $attributes);
      return back()->with('success', 'Produto inserido.');
    }

    public function update(Request $request, $id)
    {
      $options = Cart::get($id)->options;
      $arrOptions = array();
      foreach($options as $option=>$value)
          $arrOptions[$option] = $value;
      foreach($data as $index=>$value)
          $arrOptions[$index] = $value;
      $product = Products::find(Cart::get($id)->id);
      Cart::update($id, ['qty' => $request->qty, 'options' => $arrOptions]);
      return back()->with('success', 'Produto alterado com sucesso.');
    }

    public function destroy(Request $request)
    {
      Cart::remove($request->id_produto);
      return back()->with('error', 'Produto removido com sucesso.');
    }

    public function finish(Request $request)
    {
      $cartItems = Cart::content();
      if($request->isMethod('post'))
      {
        $order = new Order();
        $order->client_id = '';
        $order->salesman_id = Auth::id();
        $order->payment_id = '';
        $order->received = $request->received;
        $order->discount = $request->discount;
        $order->change = $request->change;
        $order->total = $request->total;
        $order->status = 1;
        $order->save();
        foreach (Cart::content()->unique() as $item) {
          DB::table('order_has_products')->INSERT([
            'order_id'   => $order3->id,
            'product_id' => $item->id,
            // 'size'       => $item->id,
            'price'      => number_format($item->price, 2, '.', ''),
            'qty'        => $item->qty
          ]);
          // baixa estoque
          $product = Product::find($item->id);
          $product->qty = $product->qty - $item->qty;
          $product->save();
        }
        Cart::destroy();
        return redirect()->route('shop.welcome')->with('success', 'Venda realizada com sucesso');
      }
      return view('shop.checkout', compact('cartItems'));
    }
}

resources/views/shop/checkout.blade.php
@extends('layouts.dash')
@section('content')
<!-- ========================= SECTION INTRO ========================= -->
<section class="section-intro text-white text-center">
	<div class="container d-flex flex-column"  style="min-height:70.5vh;">
		<!-- ========================= SECTION CONTENT ========================= -->


<div id="checkout-page" class="row">
	<main class="col-sm-9 mt-auto">

<div class="table-responsive">
<table class="table table-hover shopping-cart-wrap">
<thead class="text-muted">
<tr>
	<th scope="col">Imagem</th>
  	<th scope="col">Produto</th>
  	<th scope="col" width="120">Quantidade</th>
  	<th scope="col" width="120">Preço</th>
  	<th scope="col" class="text-right" width="200">Ação</th>
</tr>
</thead>
<tbody>

<?php $pricetotal = 0; ?>
	@foreach($cartItems as $item)
	<tr id="tabela-checkout">
	<td>
		<?php $pricetotal = ($item->price * $item->qty) + $pricetotal; ?>
		<figure class="media">
			<div class="img-wrap"><img src="{!! asset('images/'.$item->options['photo']) !!}" class="img-thumbnail img-sm"></div>
				
		</figure> 
	</td>
	<td>
	<p class="title text-truncate">{{$item->name}} </p>
</td>
	<td>{{$item->qty}}</td>
	<td> 
		<div class="price-wrap"> 
			<var class="price"> R$ {{$item->price}}</var> 
		</div> <!-- price-wrap .// -->
	</td>
	<td class="text-right"> 
	<form action="{{ route('shop.destroy')}}" method="POST">
		@csrf		
	    <input type="hidden" name="_method" value="DELETE">
		<input type="hidden" name="id_produto" value="{{$item->rowId}}">
	   <input type="submit" class="btn btn-danger" value="Deletar"/>
	</form>
	</td>
	</tr>
	@endforeach

</tbody>
</table>
</div> <!-- card.// -->


	</main> <!-- col.// -->
	<aside id="checkout-bloco" class="col-sm-3 text-right mt-5">
	<div>
		<p>VALOR TOTAL:<span> R$ {{$pricetotal}}</span></p>
	</div>
	<div>
		<form action="{{ route('shop.finish')}}" method="post">
		<button class="btn btn-danger">Finalizar Compra</button>
		</form>
	</div>
	</aside>
</div>

<!-- ========================= SECTION CONTENT END// ========================= -->
@endsection

resources/views/shop/list.blade.php
@extends('layouts.dash')
@section('content')
<!-- ========================= SECTION INTRO ========================= -->
<section class="section-list-product text-white text-center">
	<div class="container d-flex flex-column"  style="min-height:70.5vh;">
		
			<!-- ========================= SECTION CONTENT ========================= -->
			<div class="row-sm">
			@foreach($products as $product)
				<div class="col-md-3 col-sm-6">
					<figure class="card card-product">
						<div class="img-wrap"><img src="{!! asset('images/'.$product->photo) !!}"/></div>
						<figcaption class="info-wrap">
							<a href="{!! asset($product->id.'/produto') !!}" class="title">{{$product->name}}</a>
							<div class="price-wrap">
								<span class="price-new">${{$product->price}}</span>
								<span class="cost-new">{{$product->cost}}</span>
							</div> <!-- price-wrap.// -->
						</figcaption>
					</figure> <!-- card // -->
				</div> <!-- col // -->
			@endforeach
</div> <!-- row.// -->
</div><!-- container // -->
</section>
<!-- ========================= SECTION CONTENT .END// ========================= -->
			
@endsection

resources/views/shop/show.blade.php
@extends('layouts.dash')
@section('content')
<!-- ========================= SECTION INTRO ========================= -->
<section id="show-product" class="section-intro text-center">
<div class="container d-flex flex-column"  style="min-height:70.5vh;">

<div class="row">
<div class="col-xl-12 col-md-9 col-sm-12">
<main class="card">
	<div class="row no-gutters">
		<aside class="col-sm-6 border-right">
<article class="gallery-wrap">
<div class="img-big-wrap">
  <div> <a href="{!! asset('images/'.$product->photo) !!}" data-fancybox=""><img src="{!! asset('images/'.$product->photo) !!}"></a></div>
</div> <!-- slider-product.// -->

</article> <!-- gallery-wrap .end// -->
		</aside>
		<aside class="col-sm-6">
<article class="card-body">
<!-- short-info-wrap -->
	<h3 class="title mb-3">{{$product->name}}</h3>

<div class="mb-3">
	<var class="price h3 price-product">
		<span class="currency">Preço: R$ </span><span class="num">{{$product->price}}</span>
	</var>
</div> <!-- price-detail-wrap .// -->
<dl class="row">
  <dt class="col-sm-3">Codigo#</dt>
  <dd class="col-sm-9">{{$product->sku}}</dd>

  <dt class="col-sm-3">Localização</dt>
  <dd class="col-sm-9">{{$product->location}}</dd>
</dl>
<hr>
	<div class="row">
		<div class="col-sm-5">
			<dl class="dlist-inline">
			  <dt>Quantidade: </dt>
			  <dd>{{$product->qty}} </dd>
			</dl>  <!-- item-property .// -->
		</div> <!-- col.// -->
		<div class="col-sm-5">
			<dl class="dlist-inline">
			  <dt>Quantidade Minima: </dt>
			  <dd>{{$product->qty_min}} </dd>
			</dl>  <!-- item-property .// -->
		</div> <!-- col.// -->
	</div> <!-- row.// -->
	<hr>
	@auth
	<a href="{{ route('shop.finish') }}" class="btn  btn-sell"> Finalizar Venda </a>
	<form action="{{ route('shop.add')}}" method="post">
		@csrf
		<input type="hidden" name="id" value="{{$product->id}}">
		<button type="submit" class="btn btn-outline-dark  btn-cart"><i class="fas fa-cart-plus"></i> Adicionar no Carrinho </a>
	</form>
	@endauth
<!-- short-info-wrap .// -->
</article> <!-- card-body.// -->
		</aside> <!-- col.// -->
	</div> <!-- row.// -->
</main> <!-- card.// -->

<!-- PRODUCT DETAIL -->
<article class="card mt-3">
	<div class="card-body">
		<h4>Detalhes do Produto</h4>
		<p>{{$product->description}}	</p>
	</div> <!-- card-body.// -->
</article> <!-- card.// -->

<!-- PRODUCT DETAIL .// -->

</div> <!-- col // -->
</div> <!-- row.// -->
</div><!-- container // -->
</section>
<!-- ========================= SECTION CONTENT .END// ========================= -->
@endsection

<!--location, id_category, cor, tamanho, quantidade, qtd minima, custo, preço, status-->