routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['prefix' => '/', 'as' => 'shop.'], function () {
  Route::match( array( 'GET' ), '/', array('as' => 'welcome', 'uses' => 'ShopController@welcome'));
  Route::match( array( 'GET' ), '/buscar-produtos', array('as' => 'search', 'uses' => 'ShopController@search'));
  Route::match( array( 'GET' ), '/{ID}/produto', array('as' => 'show', 'uses' => 'ShopController@show'));
  Route::match( array( 'POST' ), '/adicionar', array('as' => 'add', 'uses' => 'ShopController@add'));
  Route::match( array( 'PUT' ), '/alterar', array('as' => 'update', 'uses' => 'ShopController@update'));
  Route::match( array( 'DELETE' ), '/excluir', array('as' => 'destroy', 'uses' => 'ShopController@destroy'));
  Route::match( array( 'GET', 'POST' ), '/finalizar', array('as' => 'finish', 'uses' => 'ShopController@finish'))->middleware('auth');
});

Auth::routes();

Route::group(['prefix' => 'painel'/*, 'middleware' => 'dash'*/, 'as' => 'dash.'], function () {
  Route::match( array( 'GET' ), '/', array('as' => 'index', 'uses' => 'Dash\DashController@index'));
  Route::match( array( 'GET' ), '/sair', array('as' => 'logout', 'uses' => 'Dash\DashController@logout'));
  Route::match( array( 'GET' ), '/minha-conta', array('as' => 'myaccount', 'uses' => 'Dash\UserController@myaccount'));
  Route::match( array( 'GET', 'PATCH' ), '/configuracoes', array('as' => 'configs', 'uses' => 'Dash\ConfigController@index'));
  Route::group(['prefix' => '/usuarios', 'as' => 'users.'], function () {
    Route::match( array( 'GET', ), '/', array('as' => 'list', 'uses' => 'Dash\UserController@all'));
    Route::match( array( 'GET', 'POST' ), '/novo', array('as' => 'create', 'uses' => 'Dash\UserController@create'));
    Route::match( array( 'GET', 'PATCH' ), '/{ID}', array('as' => 'edit', 'uses' => 'Dash\UserController@edit'));
    Route::match( array( 'DELETE' ), '/{ID}', array('as' => 'destroy', 'uses' => 'Dash\UserController@destroy'));
  });
  Route::group(['prefix' => '/produtos', 'as' => 'products.'], function () {
    Route::match( array( 'GET', ), '/todos', array('as' => 'list', 'uses' => 'Dash\ProductController@all'));
    Route::match( array( 'GET', 'POST' ), '/novo', array('as' => 'create', 'uses' => 'Dash\ProductController@create'));
    Route::match( array( 'GET', 'PATCH' ), '/{ID}', array('as' => 'edit', 'uses' => 'Dash\ProductController@edit'));
    Route::match( array( 'DELETE' ), '/{ID}', array('as' => 'destroy', 'uses' => 'Dash\ProductController@destroy'));
  });
  Route::group(['prefix' => '/estoque', 'as' => 'stock.'], function () {
    Route::match( array( 'GET' ), '/', array('as' => 'list', 'uses' => 'Dash\StockController@all'));
  });
  Route::group(['prefix' => '/pedidos', 'as' => 'orders.'], function () {
    Route::match( array( 'GET', ), '/', array('as' => 'list', 'uses' => 'Dash\OrderController@all'));
    Route::match( array( 'GET', 'PATCH' ), '/{ID}', array('as' => 'edit', 'uses' => 'Dash\OrderController@show'));
    Route::match( array( 'GET', 'PATCH' ), '/{ID}/editar', array('as' => 'edit', 'uses' => 'Dash\OrderController@edit'));
  });
  Route::group(['prefix' => '/mala-direta', 'as' => 'directmail.'], function () {
    Route::match( array( 'GET', 'POST' ), '/', array('as' => 'list', 'uses' => 'Dash\DirectEmailController@all'));
    Route::match( array( 'GET', 'PATCH' ), '/{ID}', array('as' => 'edit', 'uses' => 'Dash\DirectEmailController@edit'));
    Route::match( array( 'GET', '' ), '/{ID}/enviar', array('as' => 'send', 'uses' => 'Dash\DirectEmailController@send'));
    Route::match( array( 'DELETE' ), '/{ID}', array('as' => 'destroy', 'uses' => 'Dash\DirectEmailController@destroy'));
  });
});

app/Models/Products.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Products extends Model
{
  protected $table = 'products';
  protected $fillable = [
     'name', 'description', 'sku', 'photo', 'location',
     'id_category', 'unit', 'id_color', 'id_size',
     'qty', 'qty_min', 'cost', 'price', 'status'
  ];

  public function color()
  {
      return $this->hasOne('App\Models\Colors');
  }

  public function size()
  {
      return $this->hasOne('App\Models\Size');
  }

  public function category()
  {
      return $this->hasOne('App\Models\Categories');
  }
}

app/Http/Controllers/Dash/ConfigController.php
<?php

namespace App\Http\Controllers\Dash;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\File;
use App\Http\Controllers\Controller;

use App\Models\Settings;

use Validator;

class ConfigController extends Controller
{
    public function index(Request $request)
    {
      $data = Settings::first();
      if($request->isMethod('PATCH')) {
        $validator = Validator::make($request->all(),
          [
            'title'                     =>'required|max:255',
            'slogan'                    =>'required|max:255',
            'logo'                      =>'image|mimes:png,jpg,jpeg|max:10000|max:255',
            'email'                     =>'required|email|max:255'
          ],
          [
            'title.required'            => 'Informe o título.',
            'slogan.required'           => 'Informe o slogan.',
            'email.required'            => 'Informe um e-mail válido.',
            'email.email'               => 'Informe um e-mail válido.',
            'logo.image'                => 'Insira uma arquivo do tipo imagem (png, jpg ou jpeg).',
            'logo.mimes'                => 'Insira uma imagem do tipo png, jpg ou jpeg.',
            'logo.max'                  => 'Insira uma imagem menor que 10000px.'
          ]
        );
        if($validator->fails())
          return back()->withInput($request->all())->withErrors($validator->errors());
        $data->fill($request->all());
        $image = $data->logo;
        if($image) {
          if($image != 'default.png'){
            $path = public_path().'/images/settings/';
            File::delete($path.$image);
          }
          $imageName = uniqid() . $image->getClientOriginalName();
          $image->move('images/settings', $imageName);
          $data->logo = $imageName;
        }
        $data->save();
        return back()->with('success', 'Alterado com sucesso.');
      }
      $data = Settings::first();
      return view('dash.settings.index', compact('data'));
    }
}

app/Http/Controllers/Dash/DashController.php
<?php

namespace App\Http\Controllers\Dash;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use App\Http\Controllers\Controller;

class DashController extends Controller
{
    public function index()
    {
      return redirect()->route('shop.welcome');
    }

    public function logout()
    {
      Auth::logout();
      return redirect()->route('shop.welcome');
    }
}

app/Http/Controllers/Dash/DirectEmailController.php
<?php

namespace App\Http\Controllers\Dash;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class DirectEmailController extends Controller
{
    //
}

app/Http/Controllers/Dash/OrderController.php
<?php

namespace App\Http\Controllers\Dash;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class OrderController extends Controller
{
    //
}

app/Http/Controllers/Dash/ProductController.php
<?php

namespace App\Http\Controllers\Dash;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

use App\Models\Products;
use App\Models\Categories;
use App\Models\Colors;
use App\Models\Sizes;

use Validator;

class ProductController extends Controller
{
    public function all(Request $request)
    {
      $products = Products::get();
      return view('dash.products.list', compact('products'));
    }

    public function create(Request $request)
    {
      if($request->isMethod('post')) {
        $validator = Validator::make($request->all(),
          [
            'name'                      =>'required|max:255',
            'description'               =>'required|max:255',
            'sku'                       =>'required|max:255',
            'photo'                     =>'image|mimes:png,jpg,jpeg|max:10000|max:255',
            'location'                  =>'required|max:255',
            'id_category'               =>'required|max:255',
            'unit'                      =>'required|max:255',
            'id_color'                  =>'required|max:255',
            'id_size'                   =>'required|max:255',
            'qty'                       =>'required|max:255',
            'qty_min'                   =>'required|max:255',
            'cost'                      =>'required|max:255',
            'price'                     =>'required|max:255',
            'status'                    =>'required|max:255'
          ],
          [
            'name.required'             =>'Informe o nome.',
            'description.required'      =>'Informe a descrição.',
            'location.required'         =>'Informe a disposição do produto.',
            'id_category.required'      =>'Informe a categoria.',
            'unit.required'             =>'Informe a unidade.',
            'id_color.required'         =>'Informe a cor.',
            'id_size.required'          =>'Informe o tamanho.',
            'qty.required'              =>'Informe a quantidae.',
            'qty_min.required'          =>'Informe a quantidae mínima.',
            'cost.required'             =>'Informe o preço de custo.',
            'price.required'            =>'Informe o preço final.',
            'status.required'           =>'Informe o status.',
            'sku.required'              =>'Informe o SKU.',
            'photo.image'               =>'Insira uma arquivo do tipo imagem (png, jpg ou jpeg).',
            'photo.mimes'               =>'Insira uma imagem do tipo png, jpg ou jpeg.',
            'photo.max'                 =>'Insira uma imagem menor que 10000px.'
          ]
        );
        if($validator->fails())
          return back()->withInput($request->all())->withErrors($validator->errors());
        $product = new Products();
        $product->fill($request->all());
        $image = $request->photo;
        if($image) {
          $imageName = uniqid() . date('YmaHsi');
          $image->move('images/products', $imageName);
          $product->photo = $imageName;
        } else {
          $product->photo = 'default.png';
        }
        $product->save();
        return redirect()->route('dash.products.edit', $product->id)->with('success', 'Cadastro realizado com sucesso.');
      }
      $sizes = Sizes::Get();
      $colors = Colors::Get();
      $categories = Categories::Get();
      return view('dash.products.create', compact('product', 'sizes', 'colors', 'categories'));
    }

    public function edit(Request $request, $id)
    {
      $product = Products::find($id);
      if($request->isMethod('patch')) {
        $validator = Validator::make($request->all(),
          [
            'name'                      =>'required|max:255',
            'description'               =>'required|max:255',
            'sku'                       =>'required|max:255',
            'photo'                     =>'image|mimes:png,jpg,jpeg|max:10000|max:255',
            'location'                  =>'required|max:255',
            'id_category'               =>'required|max:255',
            'unit'                      =>'required|max:255',
            'id_color'                  =>'required|max:255',
            'id_size'                   =>'required|max:255',
            'qty'                       =>'required|max:255',
            'qty_min'                   =>'required|max:255',
            'cost'                      =>'required|max:255',
            'price'                     =>'required|max:255',
            'status'                    =>'required|max:255'
          ],
          [
            'name.required'             =>'Informe o nome.',
            'description.required'      =>'Informe a descrição.',
            'location.required'         =>'Informe a disposição do produto.',
            'id_category.required'      =>'Informe a categoria.',
            'unit.required'             =>'Informe a unidade.',
            'id_color.required'         =>'Informe a cor.',
            'id_size.required'          =>'Informe o tamanho.',
            'qty.required'              =>'Informe a quantidae.',
            'qty_min.required'          =>'Informe a quantidae mínima.',
            'cost.required'             =>'Informe o preço de custo.',
            'price.required'            =>'Informe o preço final.',
            'status.required'           =>'Informe o status.',
            'sku.required'              =>'Informe o SKU.',
            'photo.image'               =>'Insira uma arquivo do tipo imagem (png, jpg ou jpeg).',
            'photo.mimes'               =>'Insira uma imagem do tipo png, jpg ou jpeg.',
            'photo.max'                 =>'Insira uma imagem menor que 10000px.'
          ]
        );
        if($validator->fails())
          return back()->withInput($request->all())->withErrors($validator->errors());
        $product->fill($request->all());
        $product->price = number_format($request->price, 2, '.', '');
        $image = $request->photo;
        if($image) {
          if($image != 'default.png'){
            $path = public_path().'/images/products/';
            File::delete($path.$image);
          }
          $imageName = uniqid() . $image->getClientOriginalName();
          $image->move('images/products', $imageName);
          $product->photo = $imageName;
        }
        $product->save();
        return back()->with('success', 'Alterado com sucesso.');
      }
      $sizes = Sizes::Get();
      $colors = Colors::Get();
      $categories = Categories::Get();
      return view('dash.products.edit', compact('product', 'sizes', 'colors', 'categories'));
    }

    public function destroy($id)
    {
      Products::destroy($id);
      return redirect()->route('dash.products.list')->with('success', 'Removido com sucesso.');
    }
}

app/Http/Controllers/Dash/StockController.php
<?php

namespace App\Http\Controllers\Dash;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class StockController extends Controller
{
    //
}

resources/views/dash/products/create.blade.php
@extends('layouts.dash')
@section('content')
<aside class="col-sm-12">
<div id="code_register_1">
<div class="card">
<header class="card-header">
	<a href="{{ URL::previous() }}" class="float-right btn btn-outline-primary mt-1">Voltar</a>
	<h4 class="card-title mt-2">Novo Produto</h4>
</header>
<article class="card-body">
<form action="{!! route('dash.products.create') !!}" method="POST" enctype="multipart/form-data" autocomplete="off">
    @csrf
	<div class="form-row">
		<div class="col form-group">
			<label>Nome</label>
		  	<input type="text" class="form-control" name="name" placeholder="" value="{!! old('name') !!}">
		</div> <!-- form-group end.// -->
		<div class="col form-group">
			<label>Foto</label>
		  	<input type="file" class="form-control" name="photo" placeholder="">
		</div> <!-- form-group end.// -->
	</div> <!-- form-row end.// -->
<div class="form-row">
	<div class="col form-group">
		<label>Disposição do produto</label>
		<input type="text" class="form-control" placeholder="" name="location" value="{!! old('location') !!}">
	</div> <!-- form-group end.// -->
	<div class="col form-group">
			<label>Categoria:</label>
			<select class="form-control" name="id_category">
				<option value="">Selecionar</option>
				@foreach($categories as $category)
					<option value="{!! $category->id !!}">{!! $category->name !!}</option>
				@endforeach
			</select>
	</div> <!-- form-group end.// -->
	</div> <!-- form-row end.// -->
	<div class="form-row">
		<div class="col form-group">
				<label>Unidade:</label>
				<select class="form-control" name="unit">
					<option value="Unidade">Unidade</option>
					<option value="Pacote">Pacote</option>
					<option value="Conjunto">Conjunto</option>
				</select>
		</div> <!-- form-group end.// -->
		<div class="col form-group">
			<label>SKU</label>
			<input type="text" class="form-control" name="sku" placeholder="" value="{!! old('sku') !!}">
		</div> <!-- form-group end.// -->
		<div class="col form-group">
				<label>Situção:</label>
				<select class="form-control" name="status">
					<option value="active">Ativo</option>
					<option value="inactive">Inativo</option>
				</select>
		</div> <!-- form-group end.// -->
		</div> <!-- form-row.// -->
		<div class="form-row">
			<div class="col form-group">
				<label>Descrição:</label>
				<textarea name="description" class="form-control" rows="4" cols="80">{!! old('description') !!}</textarea>
			</div> <!-- form-group end.// -->
	</div> <!-- form-row.// -->
	<div class="form-row">
		<div class="col-2 form-group">
			<label>Cor:</label>
			<select class="form-control" name="id_color">
				<option value="">Selecionar</option>
				@foreach($colors as $color)
					<option value="{!! $color->id !!}">{!! $color->name !!}</option>
				@endforeach
			</select>
			</div> <!-- form-group end.// -->
			<div class="col-2 form-group">
				<label>Tamanho:</label>
				<select class="form-control" name="id_size">
					<option value="">Selecionar</option>
					@foreach($sizes as $size)
						<option value="{!! $size->id !!}">{!! $size->name !!}</option>
					@endforeach
				</select>
			</div> <!-- form-group end.// -->
			<div class="col-2 form-group">
				<label>Qtd. Mínima:</label>
						<input type="text" class="form-control" name="qty_min" placeholder="" value="{!! old('qty_min') !!}">
			</div> <!-- form-group end.// -->
			<div class="col-2 form-group">
				<label>Quantidade:</label>
						<input type="text" class="form-control" name="qty" placeholder="" value="{!! old('qty') !!}">
			</div> <!-- form-group end.// -->
			<div class="col-2 form-group">
				<label>Custo:</label>
						<input type="text" class="form-control" name="cost" placeholder="" value="{!! old('cost') !!}">
			</div> <!-- form-group end.// -->
			<div class="col-2 form-group">
				<label>Preço:</label>
						<input type="text" class="form-control" name="price" placeholder="" value="{!! old('price') !!}">
			</div> <!-- form-group end.// -->
		</div> <!-- form-row.// -->


    <div class="form-group">
        <button type="submit" class="btn btn-primary btn-block"> Salvar  </button>
    </div> <!-- form-group// -->
</form>
</article> <!-- card-body end .// -->
</div> <!-- card.// -->

</div> <!-- code-wrap.// -->
	</aside>
@endsection

resources/views/dash/products/edit.blade.php
@extends('layouts.dash')
@section('content')
<aside class="col-sm-12">
<div id="code_register_1">
<div class="card">
<header class="card-header">
	<a href="{{ URL::previous() }}" class="float-right btn btn-outline-primary mt-1">Voltar</a>
	<h4 class="card-title mt-2">Novo Produto</h4>
</header>
<article class="card-body">
	<form action="{!! route('dash.products.edit', $product->id) !!}" method="POST" enctype="multipart/form-data" autocomplete="off">
	    <input type="hidden" name="_method" value="PATCH">
			@csrf
	<div class="form-row">
		<div class="col form-group">
			<label>Nome</label>
		  	<input type="text" class="form-control" placeholder="" name="name" value="{!! $product->name !!}">
		</div> <!-- form-group end.// -->
		<div class="col form-group">
			<label>Foto</label>
		  	<input type="file" class="form-control" name="photo" placeholder="">
		</div> <!-- form-group end.// -->
	</div> <!-- form-row end.// -->
<div class="form-row">
	<div class="col form-group">
		<label>Disposição do produto</label>
		<input type="text" class="form-control" placeholder="" name="location" value="{!! $product->location !!}">
	</div> <!-- form-group end.// -->
	<div class="col form-group">
			<label>Categoria:</label>
			<select class="form-control" name="id_category">
				<option value="">Selecionar</option>
				@foreach($categories as $category)
					<option value="{!! $category->id !!}" @if($product->id_category == $category->id) selected @endif>{!! $category->name !!}</option>
				@endforeach
			</select>
	</div> <!-- form-group end.// -->
	</div> <!-- form-row end.// -->
	<div class="form-row">
		<div class="col form-group">
				<label>Unidade:</label>
				<select class="form-control" name="unit">
					<option value="Unidade" @if($product->status == 'Unidade') activated @endif>Unidade</option>
					<option value="Pacote" @if($product->status == 'Pacote') activated @endif>Pacote</option>
					<option value="Conjunto" @if($product->status == 'Conjunto') activated @endif>Conjunto</option>
				</select>
		</div> <!-- form-group end.// -->
		<div class="col form-group">
			<label>SKU</label>
			<input type="text" class="form-control" name="sku" placeholder="" value="{!! $product->sku !!}">
		</div> <!-- form-group end.// -->
		<div class="col form-group">
				<label>Situção:</label>
				<select class="form-control" name="status">
					<option value="active" @if($product->status == 'active') activated @endif>Ativo</option>
					<option value="inactive" @if($product->status == 'inactive') activated @endif>Inativo</option>
				</select>
		</div> <!-- form-group end.// -->
		</div> <!-- form-row.// -->
		<div class="form-row">
			<div class="col form-group">
				<label>Descrição:</label>
				<textarea class="form-control" name="description" rows="4" cols="80">{!! $product->description !!}</textarea>
				</div> <!-- form-group end.// -->
	</div> <!-- form-row.// -->
	<div class="form-row">
		<div class="col-2 form-group">
			<label>Cor:</label>
			<select class="form-control" name="id_color">
				<option value="">Selecionar</option>
				@foreach($colors as $color)
					<option value="{!! $color->id !!}" @if($product->id_color == $color->id) selected @endif>{!! $color->name !!}</option>
				@endforeach
			</select>
			</div> <!-- form-group end.// -->
			<div class="col-2 form-group">
				<label>Tamanho:</label>
				<select class="form-control" name="id_size">
					<option value="">Selecionar</option>
					@foreach($sizes as $size)
						<option value="{!! $size->id !!}" @if($product->id_size == $size->id) selected @endif>{!! $size->name !!}</option>
					@endforeach
				</select>
			</div> <!-- form-group end.// -->
			<div class="col-2 form-group">
				<label>Qtd. Mínima:</label>
						<input type="text" class="form-control" name="qty_min" placeholder="" value="{!! $product->qty_min !!}">
			</div> <!-- form-group end.// -->
			<div class="col-2 form-group">
				<label>Quantidade:</label>
						<input type="text" class="form-control" name="qty" placeholder="" value="{!! $product->qty !!}">
			</div> <!-- form-group end.// -->
			<div class="col-2 form-group">
				<label>Custo:</label>
						<input type="text" class="form-control" name="cost" placeholder="" value="{!! $product->cost !!}">
			</div> <!-- form-group end.// -->
			<div class="col-2 form-group">
				<label>Preço:</label>
						<input type="text" class="form-control" name="price" placeholder="" value="{!! $product->price !!}">
			</div> <!-- form-group end.// -->
		</div> <!-- form-row.// -->
    <div class="form-row">
      <div class="col form-group">
          <button type="submit" class="btn btn-warning btn-block"> Salvar  </button>
      </div> <!-- form-group end.// -->
    </div> <!-- form-row end.// -->
</form>
<form action="{!! route('dash.products.destroy', $product->id) !!}" method="POST" enctype="multipart/form-data" autocomplete="off">
	<input type="hidden" name="_method" value="DELETE">
	@csrf
	<button type="submit" class="btn btn-danger btn-block"> Excluir  </button>
</form>
</article> <!-- card-body end .// -->
</div> <!-- card.// -->
</div> <!-- code-wrap.// -->
	</aside>
@endsection

resources/views/dash/products/list.blade.php
@extends('layouts.dash')
@section('content')
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.1/css/bootstrap.css">
<link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/dataTables.bootstrap4.min.css">
<aside class="col-sm-12">
  <table id="table" class="table table-hover shopping-cart-wrap">
  <thead class="text-muted">
  <tr>
    <th scope="col">SKU</th>
    <th scope="col">Nome</th>
    <th scope="col">Estoque</th>
    <th scope="col">Status</th>
    <th scope="col"></th>
  </tr>
  </thead>
  <tbody>
  @foreach($products as $product)
  <tr>
      <td>
        <div class="form-row">
            <div class="col form-group">
                {!! $product->sku !!}
            </div> <!-- form-group end.// -->
        </div> <!-- form-row end.// -->
      </td>
      <td>
        <div class="form-row">
            <div class="col form-group">
                {!! $product->name !!}
            </div> <!-- form-group end.// -->
        </div> <!-- form-row end.// -->
      </td>
      <td>
        <div class="form-row">
            
            <div class="col form-group">
                <strong>Preço</strong><br/>
                {!! $product->price !!}
            </div> <!-- form-group end.// -->
            <div class="col form-group">
                <strong>Qtd.</strong><br/>
                {!! $product->qty !!}
            </div> <!-- form-group end.// -->
            <div class="col form-group">
                <strong>Qtd. Mín.</strong><br/>
                {!! $product->qty_min !!}
            </div> <!-- form-group end.// -->
        </div> <!-- form-row end.// -->
      </td>
      <td>
        <div class="form-row">
            <div class="col form-group">
                @if($product->status == 'active')
                  <span class="btn btn-sm btn-success float-right">Ativo</span>
                @else
                  <span class="btn btn-sm btn-danger float-right">Inactive</span>
                @endif
            </div> <!-- form-group end.// -->
        </div> <!-- form-row end.// -->
      </td>
      <td>
        <td class="text-left">
        <a href="{!! route('dash.products.edit', $product->id) !!}" class="btn btn-sm btn-info btn-round">Editar</a>
      </td>
  </tr>
  @endforeach
  </tbody>
  </table>
	</aside>

<script type="text/javascript">
  $(document).ready(function() {
    $('#table').DataTable();
  } );
</script>
@endsection