routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['prefix' => '/', 'as' => 'shop.'], function () {
  Route::match( array( 'GET' ), '/', array('as' => 'welcome', 'uses' => 'ShopController@welcome'));
  Route::match( array( 'GET' ), '/buscar-produtos', array('as' => 'search', 'uses' => 'ShopController@search'));
  Route::match( array( 'GET' ), '/{ID}/produto', array('as' => 'show', 'uses' => 'ShopController@show'));
  Route::match( array( 'POST' ), '/adicionar', array('as' => 'add', 'uses' => 'ShopController@add'));
  Route::match( array( 'PUT' ), '/alterar', array('as' => 'update', 'uses' => 'ShopController@update'));
  Route::match( array( 'DELETE' ), '/excluir', array('as' => 'destroy', 'uses' => 'ShopController@destroy'));
  Route::match( array( 'GET', 'POST' ), '/finalizar', array('as' => 'finish', 'uses' => 'ShopController@finish'))->middleware('auth');
});

Auth::routes();

Route::group(['prefix' => 'painel'/*, 'middleware' => 'dash'*/, 'as' => 'dash.'], function () {
  Route::match( array( 'GET' ), '/', array('as' => 'index', 'uses' => 'Dash\DashController@index'));
  Route::match( array( 'GET' ), '/sair', array('as' => 'logout', 'uses' => 'Dash\DashController@logout'));
  Route::match( array( 'GET' ), '/minha-conta', array('as' => 'myaccount', 'uses' => 'Dash\UserController@myaccount'));
  Route::match( array( 'GET', 'PATCH' ), '/configuracoes', array('as' => 'configs', 'uses' => 'Dash\ConfigController@index'));
  Route::group(['prefix' => '/usuarios', 'as' => 'users.'], function () {
    Route::match( array( 'GET', ), '/', array('as' => 'list', 'uses' => 'Dash\UserController@all'));
    Route::match( array( 'GET', 'POST' ), '/novo', array('as' => 'create', 'uses' => 'Dash\UserController@create'));
    Route::match( array( 'GET', 'PATCH' ), '/{ID}', array('as' => 'edit', 'uses' => 'Dash\UserController@edit'));
    Route::match( array( 'DELETE' ), '/{ID}', array('as' => 'destroy', 'uses' => 'Dash\UserController@destroy'));
  });
  Route::group(['prefix' => '/produtos', 'as' => 'products.'], function () {
    Route::match( array( 'GET', ), '/todos', array('as' => 'list', 'uses' => 'Dash\ProductController@all'));
    Route::match( array( 'GET', 'POST' ), '/novo', array('as' => 'create', 'uses' => 'Dash\ProductController@create'));
    Route::match( array( 'GET', 'PATCH' ), '/{ID}', array('as' => 'edit', 'uses' => 'Dash\ProductController@edit'));
    Route::match( array( 'DELETE' ), '/{ID}', array('as' => 'destroy', 'uses' => 'Dash\ProductController@destroy'));
  });
  Route::group(['prefix' => '/estoque', 'as' => 'stock.'], function () {
    Route::match( array( 'GET' ), '/', array('as' => 'list', 'uses' => 'Dash\StockController@all'));
  });
  Route::group(['prefix' => '/pedidos', 'as' => 'orders.'], function () {
    Route::match( array( 'GET', ), '/', array('as' => 'list', 'uses' => 'Dash\OrderController@all'));
    Route::match( array( 'GET', 'PATCH' ), '/{ID}', array('as' => 'edit', 'uses' => 'Dash\OrderController@show'));
    Route::match( array( 'GET', 'PATCH' ), '/{ID}/editar', array('as' => 'edit', 'uses' => 'Dash\OrderController@edit'));
  });
  Route::group(['prefix' => '/mala-direta', 'as' => 'directmail.'], function () {
    Route::match( array( 'GET', 'POST' ), '/', array('as' => 'list', 'uses' => 'Dash\DirectEmailController@all'));
    Route::match( array( 'GET', 'PATCH' ), '/{ID}', array('as' => 'edit', 'uses' => 'Dash\DirectEmailController@edit'));
    Route::match( array( 'GET', '' ), '/{ID}/enviar', array('as' => 'send', 'uses' => 'Dash\DirectEmailController@send'));
    Route::match( array( 'DELETE' ), '/{ID}', array('as' => 'destroy', 'uses' => 'Dash\DirectEmailController@destroy'));
  });
});

resources/views/layouts/auth.blade.php
@php
use App\Models\Settings;
$settings = Settings::First();
@endphp
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{!! $settings->title !!}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    @include('scripts.js')

    <!-- Fonts -->
    <link rel="dns-prefetch" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Raleway:300,400,600" rel="stylesheet" type="text/css">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">

    @include('scripts.css')
</head>
<body>
    <div id="app" class="page-login mb-auto" style="min-height:100vh;">
       {{-- <nav class="navbar navbar-expand-md navbar-light navbar-laravel">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Simply Easy') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                            </li>
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav> --}}

        <main class="py-4">
            @yield('content')
        </main>
    </div> 
</body>
</html>

resources/views/layouts/dash.blade.php
@php
use App\Models\Settings;
$settings = Settings::First();
@endphp
<!DOCTYPE HTML>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="author" content="Bootstrap-ecommerce by Vosidiy">

<title>{!! $settings->title !!}</title>
<link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
<link rel="shortcut icon" type="image/x-icon" href="images/favicon.ico">


@include('scripts.css')
@include('scripts.js')



</head>
<body>

@include('partials.nav-horizontal')
@auth
<div class="card filter-products col-md-11">
	<div class="card-body">
		<div class="row">
			<div class="col-md-21-24"> 
				<ul class="list-inline">
				  <li class="list-inline-item dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown">   Usuarios </a>
		            <div class="dropdown-menu p-3" style="max-width:400px";>	
				      <label class="form-check">
				      	<a href="{{ route('dash.users.create') }}">Novo </a>
				      </label>
				      <label class="form-check">
				      	<a href="{{ route('dash.users.list') }}">Listar </a>
				      </label>
		            </div> <!-- dropdown-menu.// -->
			      </li>
			      <li class="list-inline-item dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown">  Produtos </a>
		            <div class="dropdown-menu p-3" style="max-width:400px";>	
				      <label class="form-check">
				      	<a href="{{ route('dash.products.create') }}">Novo </a>
				      </label>
				      <label class="form-check">
				      	<a href="{{ route('dash.products.list') }}">Listar </a>
				      </label>
		            </div> <!-- dropdown-menu.// -->
			      </li>
			      <li class="list-inline-item dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown">  Fornecedores </a>
		            <div class="dropdown-menu p-3" style="max-width:400px";>	
				      <label class="form-check">
				      	<a href="#">Novo </a>
				      </label>
				      <label class="form-check">
				      	<a href="#">Listar </a>
				      </label>
		            </div> <!-- dropdown-menu.// -->
			      </li>
			      <li class="list-inline-item dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown">  Relatórios </a>
		            
			      </li>
			      <li class="list-inline-item dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown">  Mala Direta </a>
		            
			      </li>
			</div> <!-- col.// -->
		</div> <!-- row.// -->
			</div> <!-- card-body .// -->
		</div> <!-- card.// -->
		@endauth
@include('helpers.alert')
@yield('content')

</section>
<!-- ========================= SECTION INTRO END// ========================= -->



@include('partials.footer')


</body>
</html>